dist: xenial

language: python

compiler: g++

python:
  - 3.6

env:
  global:
    - TRAVIS_CI=true

install:
  - pip install pipenv
  - pipenv install --dev --deploy
  - sudo apt-get install -y gdb  # install gdb

before_script:
  - ulimit -c unlimited -S       # enable core dumps

after_failure:
  - PYTHON_EXECUTABLE=$(python3 -c "import sys; print(sys.executable)")
  - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
  - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" $PYTHON_EXECUTABLE -ex "thread apply all bt" -ex "set pagination 0" -batch; fi

script:
  - make testcert.cert
  - make lint
  - ./test.py -s -v --filter=test_throughput_while_adjusting_servicecount
  - pipenv check
